# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'representantes',
            },
        ),
    ]
