# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200624_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Representantes',
            new_name='Revendedor',
        ),
        migrations.AlterModelTable(
            name='revendedor',
            table='revendedores',
        ),
    ]
