# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200627_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaCashBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=200)),
                ('Porcentagem', models.FloatField()),
                ('FaixaTop', models.FloatField()),
            ],
            options={
                'db_table': 'faixa_cashback',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('ValorCompra', models.FloatField()),
                ('Status', models.CharField(default=b'Em Validacao', max_length=12)),
                ('FaixaCashBack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixacash', to='myapp.FaixaCashBack')),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
        migrations.RenameField(
            model_name='revendedor',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='revendedor',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='revendedor',
            old_name='nome',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='revendedor',
            old_name='senha',
            new_name='Senha',
        ),
        migrations.AddField(
            model_name='vendas',
            name='Revendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revendedor', to='myapp.Revendedor'),
        ),
    ]
