# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200627_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixacashback',
            name='FaixaIni',
            field=models.FloatField(default=0),
        ),
    ]
