# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_faixacashback_faixaini'),
    ]

    operations = [
        migrations.AddField(
            model_name='revendedor',
            name='Super',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='Status',
            field=models.CharField(blank=True, default=b'Em Validacao', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='ValorCompra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
