# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200628_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Compras',
        ),
        migrations.AlterModelTable(
            name='compras',
            table='compras',
        ),
    ]
